name: telematica-api
definition: src
generators:
  - name: fernapi/fern-java
    version: 0.0.42
    generate: true
    config:
      packagePrefix: com.telematica
      mode: client
  - name: fernapi/fern-typescript
    version: 0.0.106
    generate: true
    config:
      mode: client
